// Class automatically generated by Dev-C++ New Class wizard

#ifndef FILELIST_H
#define FILELIST_H
#include "wx/string.h"
#include "wx/hashmap.h"
#include "wx/treelistctrl.h"
/**
 * No description
 */
class FileListElement
{
	public:
		// class constructor
		FileListElement();
		// class destructor
		~FileListElement();
		wxString FolderPath;
		wxString Filename;
		wxString FullPath;
		wxTreeItemId item;
};

WX_DECLARE_STRING_HASH_MAP( FileListElement*, FileList );
//WX_DECLARE_LIST(FileListElement, FileList);



#endif // FILELIST_H
