// Class automatically generated by Dev-C++ New Class wizard

#include "filelist.h" // class's header file

// class constructor
FileListElement::FileListElement()
{
	// insert your code here
}

// class destructor
FileListElement::~FileListElement()
{
	// insert your code here
}

//#include <wx/listimpl.cpp>
//WX_DEFINE_LIST(FileList);
